apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic
  namespace: tbs
spec:
  builder:
    kind: ClusterBuilder
    name: default
  serviceAccount: default
  source:
    git:
      revision: v1.1
      url: https://github.com/jigsheth57/spring-petclinic
  tag: harbor.run.haas-222.pez.pivotal.io/tbs/spring-petclinic
