apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: fe-time-tracking
  namespace: default
spec:
  builder:
    kind: ClusterBuilder
    name: default
  serviceAccount: default
  source:
    git:
      revision: v1.6
      url: https://github.com/jigsheth57/fe-time-tracking
  tag: harbor.run.haas-222.pez.pivotal.io/tbs/fetimetracking
